# =========================
# Kitty Configuration - Nordic Theme
# =========================

allow_remote_control yes

window_padding_width 10 

# Font Settings
font_family        FiraCode Nerd Font
font_size          10.0
bold_font          auto
italic_font        auto
bold_italic_font   auto

# Scrollback
scrollback_lines    10000

# Colors and Appearance
include /home/thinus/.config/kitty/colour-schemes/nord.conf

# foreground         
background_opacity 0.8

# Cursor Settings
cursor_shape        block
cursor #BFBFBF
       

# Tabs and Title Bar
enabled_layouts     fat
tab_bar_edge        bottom
tab_bar_style       powerline
tab_powerline_style slanted
tab_title_template "{index}: {title[13:30]}…"

# Tab Colors
active_tab_background   #BD93F9
active_tab_foreground   #282A36
inactive_tab_background #44475A
inactive_tab_foreground #F8F8F2  
tab_bar_background      #282A36 

# Tab Styling
tab_fade               1
tab_separator         "  |  "
active_tab_font_style  italic
inactive_tab_font_style normal

# Keybindings
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard

# Zoom In / Out with Ctrl + + and Ctrl + -
map ctrl+equal     increase_font_size
map ctrl+minus     decrease_font_size
map ctrl+0         reset_font_size

# Zoom with Ctrl + Mouse Wheel
map ctrl+wheel_up   increase_font_size
map ctrl+wheel_down decrease_font_size

confirm_os_window_close 0

cursor_thickness 2.0


