# appearance.conf — Fonts, Gaps, Borders, Colors
# ----------------------------------------------

# Font
font pango:MesloLGS NF 10

# GTK Theme
exec --no-startup-id env GTK_THEME=Nordic-darker-v40

# Window Borders & Gaps
for_window [class="^.*"] border pixel 2.5
gaps inner 5
gaps outer 5

# Nord Theme Colors
client.focused          #88C0D0  #88C0D0  #2E3440  #88C0D0
client.unfocused        #4C566A  #4C566A  #D8DEE9  #4C566A
client.focused_inactive #434C5E  #434C5E  #81A1C1  #434C5E
client.placeholder      #3B4252  #3B4252  #D8DEE9  #3B4252
client.urgent           #BF616A  #BF616A  #ECEFF4  #BF616A
client.background       #2E3440

