# Autostart Applications
# ----------------------

# Core Services
exec_always --no-startup-id autotiling
exec --no-startup-id /usr/bin/dunst
exec --no-startup-id picom --config ~/.config/picom/picom.conf
exec_always --no-startup-id numlockx on
exec --no-startup-id sh -c "sleep 2 && /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &"
exec_always --no-startup-id sh -c "sleep 2 && ~/.config/polybar/launch.sh"
exec_always --no-startup-id xscreensaver -nosplash

# Tray Applications
exec --no-startup-id blueberry-tray
exec --no-startup-id nm-applet

# Optional Services
exec --no-startup-id dropbox start -i
#exec --no-startup-id /home/thinus/scripts/bing-wallpaper/bing-wallpaper.sh
exec --no-startup-id nitrogen --restore
# exec --no-startup-id onedrive --monitor
exec --no-startup-id /home/thinus/applications/pcloud

# Start MEGAcmd server
exec --no-startup-id megacmd-server

# Start syncing ~/MEGA with /MEGAsync after server is ready
exec --no-startup-id sh -c 'sleep 2 && mega-sync ~/MEGA /MEGAsync'

# Start battery warning script
exec --no-startup-id ~/scripts/BatteryWarn/BatteryWarn.sh


