# Window Management
bindsym $mod+q kill

# Change Focus (Vim + Arrow)
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# Moving Focused Windows (Arrow only)
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# Window Layout
bindsym $mod+v split v
#bindsym $mod+h split h   # Optional horizontal split
bindsym $mod+f fullscreen toggle
bindsym $mod+a focus parent

# Window Resizing
bindsym $mod+Mod1+Ctrl+Right resize shrink width 5 px
bindsym $mod+Mod1+Ctrl+Up resize grow height 5 px
bindsym $mod+Mod1+Ctrl+Down resize shrink height 5 px
bindsym $mod+Mod1+Ctrl+Left resize grow width 5 px

# Floating
bindsym $mod+Shift+space floating toggle
floating_modifier $mod

# Menu Launchers
bindsym $mod+space exec --no-startup-id rofi -show drun -font "MesloLGS NF 10"
bindsym $mod+slash exec --no-startup-id rofi -show window -font "MesloLGS NF 10"
bindsym $mod+Mod1+a exec --no-startup-id ~/scripts/launchers/ai-launcher.sh
bindsym $mod+Mod1+m exec --no-startup-id ~/scripts/launchers/music-launcher.sh
bindsym $mod+Mod1+e exec --no-startup-id ~/scripts/launchers/edu-launcher.sh
bindsym $mod+Mod1+s exec --no-startup-id ~/scripts/launchers/social-launcher.sh
bindsym $mod+Mod1+o exec --no-startup-id ~/scripts/launchers/office-launcher.sh
bindsym $mod+Mod1+d exec --no-startup-id ~/scripts/launchers/design-launcher.sh
# Application Shortcuts
bindsym $mod+F6 exec --no-startup-id vlc
bindsym $mod+equal exec --no-startup-id galculator
bindsym $mod+z exec zathura
bindsym $mod+r exec --no-startup-id kitty -e ranger
#bindsym $mod+l exec --no-startup-id /home/thinus/.local/share/LightBurn/LightBurn

# Screenshot
bindsym $mod+Print exec --no-startup-id flameshot gui

