# System Management Keybindings
# -----------------------------

# Power Menu / Log Out
# --------------------
bindsym $mod+Shift+e exec --no-startup-id ~/.config/i3/scripts/powermenu

# Sleep and Hibernation
# ---------------------
#bindsym $mod+Mod1+s exec --no-startup-id systemctl suspend
#bindsym $mod+Mod1+h exec --no-startup-id systemctl hibernate

# Lock Screen
# -----------
bindsym $mod+Shift+l exec --no-startup-id /usr/bin/i3lock-fancy-multimonitor -b=0x8
# Auto-lock after 10 minutes of inactivity
exec --no-startup-id xautolock -time 10 -locker "/usr/bin/i3lock-fancy-multimonitor -b=0x8"

# Screensaver
# -----------
# Start a screensaver
bindsym $mod+x exec --no-startup-id ~/scripts/cmatrix/cmatrix.sh
# Kill the screensaver
bindsym $mod+Shift+x exec --no-startup-id ~/scripts/cmatrix/kill-cmatrix.sh

# i3 Control
# ----------
# Restart i3
bindsym $mod+Shift+r restart
# Reload configuration file
bindsym $mod+Shift+c reload

