# Dracula Color Palette

# Background and foreground colors
background          #282A36
foreground          #F8F8F2

# Colors 0-15 (Dracula colors)
color0              #000000
color1              #FF5555
color2              #50FA7B
color3              #F1FA8C
color4              #BD93F9
color5              #FF79C6
color6              #8BE9FD
color7              #BFBFBF
color8              #4D4D4D
color9              #FF6E6E
color10             #69FF94
color11             #FFFFA5
color12             #D6ACFF
color13             #FF92DF
color14             #A4FFFF
color15             #FFFFFF

# Additional color settings
cursor              #F8F8F2
